version: Beta0

#extends:
#  - ".piper/dev-setup.yml"
#
# $ piper run cd-status start-mariadb
#

# ${ppty:hello} - properties
# ${cfg:sub_script_prefix} - configs
# ${env:JAVA_HOME} - envs

config:
  os: linux
  sub_script_prefix: "@"

properties:
  hello: "Hello World!!!"
  youtube: "youtube.com"
  JAVA_BIN: "${env:JAVA_HOME}/bin/java"

scripts:

  java-version:
    description: "Java Version"
    steps:
      - "@ping"
      - "${ppty.JAVA_BIN} -version"
      - "dir ${env:JAVA_HOME}"

  docker-stats:
    description: "Just Hello & PING"
    steps:
      - "@java-version"
      - "docker stats"
    validators:
      - type: "LINE_COUNT"
        parameters:
          threshold: 5

  test-echo:
    description: "Just Hello & PING"

    steps:
      - "@java-version"
      - "@docker-stats"
      - "tasklist"

    validators:
      - type: "LINE_COUNT"
        parameters:
          threshold: 5
      - type: "EXPECTED_STRING"
        parameters:
          text:
            - "WUDFHost"
      - type: "WAIT_FOR"
        parameters:
          unit: MINUTES
          time: 1

  test-run:
    description: "Test Run"

    properties:
      JAVA_BIN: "${env:JAVA_HOME}/bin/java"

    validators:
      - type: "LINE_COUNT"
        parameters:
          threshold: 2500
      - type: "EXPECTED_STRING"
        parameters:
          text:
            - "stop-word"
      - type: "WAIT_FOR"
        parameters:
          unit: SECONDS
          time: 10

    steps:
      - "dir ${env:JAVA_HOME}"
      - "ipconfig /release"
      - "${JAVA_BIN} -version"
      - "@test-echo"
      - "ping -n 5 ${ppty.youtube}"

  ping:
    description: "PING Domain!"

    validators:
      - type: "WAIT_FOR"
        parameters:
          unit: SECONDS
          time: 10
    steps:
      - "echo ${ARGS[0]} ${ARGS[1]} ${ARGS[2]}"
      - "ping -n 10 ${ARGS[2]}"