version: Beta0

#
# $ piper run cd-status start-mariadb
#

# ${ppty:hello} - properties
# ${cfg:sub_script_prefix} - configs
# ${env:JAVA_HOME} - envs

extends:
  - ".piper/.piper.dev.yaml"
  - ".piper/.piper.ubuntu.yaml"

config:
  os: linux
  sub_script_prefix: "@"

properties:
  hello: "Hello ${cfg:name}!!!"
  youtube: "youtube.com"
  JAVA_BIN: "${env:JAVA_HOME}/bin/java"

scripts:
  all:
    description: "Run All"
    steps:
      - "@java-version"
      - "@ping"
      - "@docker-stats"
  java-version:
    description: "Java Version"
    steps:
      - "${ppty.JAVA_BIN} -version"
  docker-stats:
    description: "Docker Stats (for 10 lines)"
    steps:
      - "docker stats"
    validators:
      - type: "LINE_COUNT"
        parameters:
          threshold: 10
  ping:
    description: "PING Domain!"
    validators:
      - type: "WAIT_FOR"
        parameters:
          unit: SECONDS
          time: 10
    steps:
      - "/bin/ping ${ARGS[2]}"